version: '3.8'

services:
  mongo:
    image: mongo:latest
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    networks:
      - backend
    build:
      context: ./apps/web
      dockerfile: web.dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:8901/graphql

  backend:
    networks:
      - backend
    build:
      context: ./apps/api
      dockerfile: api.dockerfile
      args:
        MONGO_URI: mongodb://mongo:27017/newsdb1
    ports:
      - "8901:8901"
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsdb1
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
